### ISSUE TITLE
PatchMatchFlow - StartLoggingGlobalMotionFlows not working

### ISSUE THREAD

**Issue by rivetti22** [SensorsINI/jaer#37]
Hi there,

I'm trying to save the optical flow data to a file and from my understanding, it is done using the StartLoggingGlobalMotionFlows function. However, when I try to do so, I input the file name in which I want to store the data, and I get a "File not found" exception.

![Screenshot from 2021-02-15 19-57-38](https://user-images.githubusercontent.com/38293419/107988544-2af87380-6fc8-11eb-8c6e-b1cb93d56544.png)

I named the file "log_test", but as seen in the screenshot it appends date and time information to the original name I gave it. I believe this the cause of this issue. Can you please help me? I would be very thankful.

**Comment by wzygzlm** [comment]
Hi Alessio,

Thanks for reporting the bug. This exception is caused by the upgrade for the TobiLogger. Patchmatchflow uses this logger to store data. Before the logger upgrade, the user has to specify a concrete path. Now we support to set to use the home folder as the default path. 

Anyway, this might not be important for end-user. I pushed a new commit to fix it. Check it.

**Comment by rivetti22** [comment]
> Hi Alessio,
> 
> Thanks for reporting the bug. This exception is caused by the upgrade for the TobiLogger. Patchmatchflow uses this logger to store data. Before the logger upgrade, the user has to specify a concrete path. Now we support to set to use the home folder as the default path.
> 
> Anyway, this might not be important for end-user. I pushed a new commit to fix it. Check it.

**Comment by rivetti22** [comment]
Hi Min,

First of all, thank you for the fast reply. I just tested it and it is working perfectly! Now I can just give a name to the file and it will store the logged data in that file, in the chosen path. Thank you for your help.
