### ISSUE TITLE
ZebrafishMedianTracker.java doesnt compile

### ISSUE THREAD

**Issue by ru1sb** [SensorsINI/jaer#7]
just delete this file to be able to start jAER, otherwise you will get the error: "cannot load or find main class"

**Comment by llongi** [comment]
Hi, I cannot reproduce that, the ZebrafishMedianTracker compiles fine on Eclipse for me.
Do you have Java 1.8 installed? How are you starting jAER?
If you are using the shell script on Linux or the EXEs on Windows, you must use a [release](https://github.com/SensorsINI/jaer/releases) because the file dist/jAER.jar is only present inside the jaer-dist.zip release file. The error you get usually indicates that file is missing.
If you are using the developer Git checkout, the file is not present, and is built by the NetBeans or Eclipse IDEs when you first open the project.
